### ISSUE TITLE
[PE-D][Tester A] UI images inaccurate

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-1/tp#161] opened 2022-10-29 03:24 UTC
For some screenshots of the product, the images are inaccurate and refer to the AB3 UI. For example, the image under find:

![image.png](https://raw.githubusercontent.com/ConradLew/ped/main/files/c553777d-ceb4-48cf-bbed-dca9aa85948f.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ConradLew/ped#11

**Comment by e1010101** [comment] 2022-10-29 12:56
Duplicate of #162.

**Closed as completed by e1010101** 2022-10-29 12:56 UTC
Labels: duplicate
