### ISSUE TITLE
[PE-D][Tester E] Changes are not saved.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#158] opened 2022-10-29 03:15 UTC
As mentioned in the UG:

"Watson’s data is saved in the hard disk automatically after any command that changes the data. There is no need to save manually."

I exited the app and restarted it. My changes were not reflected and I got back the default sample data instead.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: marcuslowhuiyu/ped#12

**Comment by e1010101** [comment] 2022-10-29 13:52
Could not reproduce issue on Windows.

Steps taken:
1) Download the .jar file from this repo under releases
2) Ran the .jar file from my Downloads folder (write access granted)
3) Run "delete 1", result was that student "Alex Yeoh" was deleted
3a) Exit the app by clicking on the "X" button on the top right of the application
3b) Exit the app by clicking "File" on the top left of the application, followed by "Exit"
4) Data was persistent through both attempts

**Comment by e1010101** [comment] 2022-10-30 13:37
Fixed in #186.

**Closed as completed by e1010101** 2022-10-30 13:37 UTC
Labels: type.Bug, priority.High, severity.High
